[versions]

# Minecraft
minecraft = "1.21.5"
loom = "1.10-SNAPSHOT"
loader = "0.16.10"

# Kotlin
ksp = "2.1.20-2.0.0"
kotlin = "2.1.20"
fabrickotlin = "1.13.2+kotlin.2.1.20"

# Dependencies
fabric = "0.119.5+1.21.5"
skyblockapi = "1.0.0-beta.114"
hypixelapi = "1.0.1+build.1+mc1.21"
rconfig = "3.5.5"
rconfigkt = "3.5.9"
olympus = "1.3.2"
rlib = "3.5.0"
meowdding-lib = "1.0.18"
meowdding-ktmodules = "1.0.3"

# Dev Dependencies
devauth = "1.2.1"

# Codegen
kotlin_poet = "2.2.1-SNAPSHOT"
kotlin_poet_ksp = "2.2.0-SNAPSHOT"

[libraries]

# Codegen
kotlin_poet = { module = "me.owdding.kotlinpoet:kotlinpoet-jvm", version.ref = "kotlin_poet" }
kotlin_poet_ksp = { module = "me.owdding.kotlinpoet:ksp", version.ref = "kotlin_poet_ksp" }
ksp = { module = "com.google.devtools.ksp:symbol-processing-api", version.ref = "ksp" }

minecraft = { module = "com.mojang:minecraft", version.ref = "minecraft" }
loader = { module = "net.fabricmc:fabric-loader", version.ref = "loader" }
fabric = { module = "net.fabricmc.fabric-api:fabric-api", version.ref = "fabric" }
fabrickotlin = { module = "net.fabricmc:fabric-language-kotlin", version.ref = "fabrickotlin" }
skyblockapi = { module = "tech.thatgravyboat:skyblock-api-1.21.5", version.ref = "skyblockapi" }
hypixelapi = { module = "maven.modrinth:hypixel-mod-api", version.ref = "hypixelapi" }
rconfig = { module = "com.teamresourceful.resourcefulconfig:resourcefulconfig-fabric-1.21.5", version.ref = "rconfig" }
rconfigkt = { module = "com.teamresourceful.resourcefulconfigkt:resourcefulconfigkt-fabric-1.21.5", version.ref = "rconfigkt" }
olympus = { module = "earth.terrarium.olympus:olympus-fabric-1.21.5", version.ref = "olympus" }
rlib = { module = "com.teamresourceful.resourcefullib:resourcefullib-fabric-1.21.5", version.ref = "rlib" }
meowdding-lib = { module = "me.owdding.meowdding-lib:meowdding-lib-1.21.5", version.ref = "meowdding-lib" }
meowdding-ktmodules = { module = "me.owdding.ktmodules:KtModules", version.ref = "meowdding-ktmodules" }

devauth = { module = "me.djtheredstoner:DevAuth-fabric", version.ref = "devauth" }

[plugins]
loom = { id = "fabric-loom", version.ref = "loom" }
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
