[versions]

fabric-loader = "0.16.10"
fabric-language-kotlin = "1.13.4+kotlin.2.2.0"
fabric-api = "0.133.4"

kotlin-symbol-processor = "2.2.0-2.0.2"
kotlin_poet = "1.0.1"
kotlin_poet_ksp = "1.0.1"

skyblockapi = "3.0.25"
hypixelapi = "1.0.1+build.1+mc1.21"
mixinconstraints = "1.0.7"

rconfigkt = "3.5.12"

meowdding-lib = "3.0.3"
meowdding-ktmodules = "1.0.8"

terrarium-cloche = "0.13.5"

[libraries]

fabric-language-kotlin = { module = "net.fabricmc:fabric-language-kotlin", version.ref = "fabric-language-kotlin" }

skyblockapi = { module = "tech.thatgravyboat:skyblock-api", version.ref = "skyblockapi" }
hypixelapi = { module = "maven.modrinth:hypixel-mod-api", version.ref = "hypixelapi" }

resourcefulkt-config = { module = "com.teamresourceful.resourcefulconfigkt:resourcefulconfigkt-fabric-1.21.5", version.ref = "rconfigkt" }

meowdding-lib = { module = "me.owdding.meowdding-lib:meowdding-lib", version.ref = "meowdding-lib" }
meowdding-ktmodules = { module = "me.owdding.ktmodules:KtModules", version.ref = "meowdding-ktmodules" }

mixinconstraints = { module = "com.moulberry:mixinconstraints", version.ref = "mixinconstraints" }

# Codegen
kotlin_poet = { module = "me.owdding.kotlinpoet:kotlinpoet-jvm", version.ref = "kotlin_poet" }
kotlin_poet_ksp = { module = "me.owdding.kotlinpoet:ksp", version.ref = "kotlin_poet_ksp" }
ksp = { module = "com.google.devtools.ksp:symbol-processing-api", version.ref = "kotlin-symbol-processor" }

[plugins]
terrarium-cloche = { id = "earth.terrarium.cloche", version.ref = "terrarium-cloche" }

kotlin-symbol-processor = { id = "com.google.devtools.ksp", version.ref = "kotlin-symbol-processor" }
